name: Vercel Deploy

on:
  push:
    branches:
      - master
  pull_request: null

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ !github.event.pull_request.head.repo.fork }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Check Branch
        id: branch
        if: ${{ github.ref  == 'refs/heads/master' }}
        run: |
          echo "args=--prod" >> $GITHUB_OUTPUT
          echo "comment=false" >> $GITHUB_OUTPUT

      - name: Deploy
        uses: amondnet/vercel-action@4b001a441d80e00aeed3680a3719d1d8b95998c5 # v42.2.1
        with:
          vercel-args: ${{ steps.branch.outputs.args }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: ${{ steps.branch.outputs.comment != 'false' }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
